project/pages/urls.py
from django.urls import path
from pages.views import home, GamesList, privacy, delete_game

urlpatterns = [
    path(route='', view=home, name='home'),
    path(route='privacy/', view=privacy, name='privacy'),
    path('games/', GamesList.as_view(), name='games'),
    path('delete_game/<int:id>', view=delete_game, name='delete_game')
]

project/scorer/urls.py
from django.urls import path
from .views import game

urlpatterns = [
    path(route='<slug:slug>/', view=game, name='game'),
]

project/scorer/models.py
from django.db import models
from datetime import datetime
from django.utils.crypto import get_random_string
from users.models import CustomUser
from django.conf import settings

class Game(models.Model):
    """
    Game has a one-to-many relationship with Round (a Game may have several
    Rounds, but a Round may only belong to one Game).
    Game has a one-to-many relationship with Player (a Game may have several
    Players, but a Player may only belong to one Game. This may change in the
    future to a many-to-many relationship to allow tracking of player stats over
    several Games).
    """
    slug = models.SlugField(
        unique=True,
        blank=True) # only so I can migrate after initial migration....
    organizer = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        related_name="organizer",
        default=1, # default to admin
        on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)

    # def get_absolute_url(self):
    #     return "/game/%i" % self.slug

    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     return super(Game, self).__init__(*args, **kwargs)


    def save(self, *args, **kwargs):
        
        # only add slug and organizer fields on first save
        if not self.slug:

            self.slug = get_random_string(7)
            # check for unique slug
            slug_is_wrong = True
            while slug_is_wrong:
                slug_is_wrong = False
                other_objs_with_slug = type(self).objects.filter(slug=self.slug)
                if len(other_objs_with_slug) > 0:
                    slug_is_wrong = True
                    self.slug = get_random_string(7)

        # save the object
        super().save(*args, **kwargs)
       

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('game', kwargs = {'slug': self.slug})


class Player(models.Model):
    """
    Player has a many-to-one relationship with Game (a Player can only belong to
    one Game, but a Game can have several Players).
    """
    name = models.CharField(
        max_length=30)
    game = models.ForeignKey(
        to=Game,
        on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Round(models.Model):
    """
    Round has a many-to-one relationship with Game (a Round belongs to only one
    Game, but a Game may have several Rounds).
    """
    game = models.ForeignKey(
        to=Game,
        on_delete=models.CASCADE)
    
    # def __str__(self):
    #     return self.id


class Score(models.Model):
    """
    Score has a one-to-many relationship with Player (a Score can only belong to
    one Player, but a Player can have many Scores).
    Score has a one-to-many relationship with Round (a Score can only belong to
    one Round, but a Round can have many Scores).
    """
    # ensure only one score is added for a given Round/Player combination
    # class Meta:
        # unique_together = (("game_round", "player"), )
    
    game_round = models.ForeignKey(
        to=Round,
        on_delete=models.CASCADE)
    player = models.ForeignKey(
        to=Player,
        on_delete=models.CASCADE)
    value = models.IntegerField(
        default=0)

    # def __str__(self):
    #     return "Round %s, Player = %s, Score = %s" % (self.game_round, self.player, self.value)
    

# python manage.py shell
# from scorer.models import Game,Player,Round,Score
# myg = Game.objects.get(slug='1XuB8Bk')
# myg.player_set.all()
# myp=myg.player_set.all()[1]

# newround = Round(game=myg)
# newscore = Score(game_round=newround, player=myg.player_set.all()[1], value=5)

# myp = myg.player_set.all()[7]
# myr = myg.round_set.all()[1]
# newscore = Score(game_round=myr, player=myp, value=2)

project/scorer/forms.py
from django.forms import ModelForm
from .models import Game, Player, Round, Score
from django.forms import modelformset_factory


class CreateGameForm(ModelForm):
    class Meta:
        model = Game
        exclude = ['organizer']


class AddPlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = ['name', 'game']


class AddRoundForm(ModelForm):
    class Meta:
        model = Round
        fields = ['game']


class ScoreForm(ModelForm):
    class Meta:
        model = Score
        fields = ['game_round', 'player', 'value']

project/scorer/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from scorer.models import Game, Player, Score, Round
from .forms import AddPlayerForm, AddRoundForm, ScoreForm
from django.urls import reverse
from django.forms import modelformset_factory
from django.db.models import Sum

def game(request, slug):
    this_game = Game.objects.get(slug=slug)
    players = this_game.player_set.all()
    rounds = this_game.round_set.all()
    latest_round = rounds.last()
    add_player_form = AddPlayerForm(initial={'game': this_game})
    add_round_form = AddRoundForm(initial={'game': this_game})
    AddScoreFormSet = modelformset_factory(Score, form=ScoreForm, fields=('game_round','player','value'), extra=0)
    
    # get total scores
    # https://stackoverflow.com/questions/45547674/how-to-execute-a-group-by-count-or-sum-in-django-orm/45547675
    running_scores = Score.objects.filter(game_round__id__in=rounds, player_id__in=players).values('player_id').order_by('player_id').annotate(total=Sum('value'))
        
    # the queryset filtering won't work if we haven't added a Round to this game
    # yet, so check if that's the case; otherwise, create empty formset
    if latest_round is not None and players is not None:
        formset = AddScoreFormSet(queryset=Score.objects.filter(player_id__in=players, game_round__id__startswith=latest_round.id))
    else:
        formset = AddScoreFormSet(queryset=Score.objects.none())

    # if POST (someone's clicked a button...)
    if request.method == 'POST':
       
        # if the POST request is to add another Player
        if 'add_player' in request.POST:
            add_player_form = AddPlayerForm(request.POST)
            if add_player_form.is_valid():
                add_player_form.save()
                # get this new player and add a placeholder score of 0
                new_player = this_game.player_set.all().last()
                new_score = Score(game_round=latest_round, player=new_player, value=0)
                new_score.save()

                return HttpResponseRedirect(reverse('game', kwargs = {'slug': this_game.slug}))
                
        # if the POST request is to add another set of Scores
        # ... also add another empty Round
        elif 'add_score' in request.POST:
            formset = AddScoreFormSet(request.POST)
            # if formset.is_valid():
            formset.save()

            new_round = Round(game=this_game)
            new_round.save()   
            new_round = this_game.round_set.all().last()
            for player in players:
                new_score = Score(game_round=new_round, player=player, value=0)
                new_score.save()         

            return HttpResponseRedirect(reverse('game', kwargs = {'slug': this_game.slug}))


    # else this is a GET request, just render blank forms
    else:
        # only add player to the current game by default. selector is hidden.
        add_player_form = AddPlayerForm(initial={'game': this_game})
        add_round_form = AddRoundForm(initial={'game': this_game})

    context = {
        "this_game": this_game,
        "add_player_form": add_player_form,
        "add_round_form": add_round_form,
        "players": players,
        "running_scores": running_scores,
        "rounds": rounds,
        "latest_round": latest_round,
        "formset": formset,
    }

    return render(request, template_name='scorer/game.html', context=context)



project/templates/scorer/game.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Game room{% endblock title %}

{% block content %}
<h3>Players</h3>
<p>
    {{ players|join:", "}}
</p>

<form action="" method="post">
    {% csrf_token %}
    <div class="input-group mb-3" style="flex-direction: row;">
        <input type="text" class="form-control" name="name" autofocus=""
            autocapitalize="none" autocomplete="none" placeholder="Name"
            aria-label="Name" maxlength="30" required="" id="id_name">
    </div>
    <div hidden class="input-group mb-3">
        <select name="game" required="" id="id_game">
            <option value="{{this_game.id}}"></option>
        </select>
    </div>
    <input type="submit" name="add_player" class="btn btn-primary" value="Add player">
</form>
<br />
<br />

<h3>Scoreboard</h3>

<div class="table-responsive">
    <table class="table table-striped table-hover" style="text-align: center;">
        <thead class="thead-dark">
            <tr style="border-bottom:groove; font-weight:500;">
                <th style="width: 10%">
                    Round
                </th>
                {% for player in players %}
                <th style="width: 10%">
                    {{ player.name }}
                </th>
                {% endfor %}
            </tr>
        </thead>
        {% for round in rounds %}
        <tr>
            <td>
                {{ forloop.counter }}
            </td>
            {% for score in round.score_set.all %}
            <td>
                {{ score.value }}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
        <tr style="border-bottom:groove; border-top:groove; font-weight:500;">
            <td>
                Total
            </td>
            {% for score in running_scores %}
            <td>
                {{ score.total }}
            </td>
            {% endfor %}
        </tr>
        <form method="post">
            <div style="vertical-align:middle;">
                <tr>
                    <td>
                        <input type="submit" name="add_score" id="add_score" class="btn
                        btn-primary" value="Update round {{ rounds|length}} ">
                    </td>
                    {% csrf_token %}
                    {{ formset.management_form }}
                    {% for form in formset %}
                    <td>
                        <div hidden class="input-group">
                            {{ form.player }}
                        </div>
                        <div hidden class="input-group">
                            {{ form.game_round }}
                        </div>
                        <div class="input-group">
                            {{ form.value }}
                        </div>
                        <div hidden class="input-group">
                            {{ form.id }}
                        </div>
                    </td> 
                    {% endfor %}
                </tr>
            </div>   
        </form> 
    </table>
</div>


<br />

{% endblock content %}