project/pages/urls.py
from django.urls import path
from pages.views import home, GamesList, privacy, delete_game

urlpatterns = [
    path(route='', view=home, name='home'),
    path(route='privacy/', view=privacy, name='privacy'),
    path('games/', GamesList.as_view(), name='games'),
    path('delete_game/<int:id>', view=delete_game, name='delete_game')
]

project/scorer/models.py
from django.db import models
from datetime import datetime
from django.utils.crypto import get_random_string
from users.models import CustomUser
from django.conf import settings

class Game(models.Model):
    """
    Game has a one-to-many relationship with Round (a Game may have several
    Rounds, but a Round may only belong to one Game).
    Game has a one-to-many relationship with Player (a Game may have several
    Players, but a Player may only belong to one Game. This may change in the
    future to a many-to-many relationship to allow tracking of player stats over
    several Games).
    """
    slug = models.SlugField(
        unique=True,
        blank=True) # only so I can migrate after initial migration....
    organizer = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        related_name="organizer",
        default=1, # default to admin
        on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)

    # def get_absolute_url(self):
    #     return "/game/%i" % self.slug

    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     return super(Game, self).__init__(*args, **kwargs)


    def save(self, *args, **kwargs):
        
        # only add slug and organizer fields on first save
        if not self.slug:

            self.slug = get_random_string(7)
            # check for unique slug
            slug_is_wrong = True
            while slug_is_wrong:
                slug_is_wrong = False
                other_objs_with_slug = type(self).objects.filter(slug=self.slug)
                if len(other_objs_with_slug) > 0:
                    slug_is_wrong = True
                    self.slug = get_random_string(7)

        # save the object
        super().save(*args, **kwargs)
       

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('game', kwargs = {'slug': self.slug})


class Player(models.Model):
    """
    Player has a many-to-one relationship with Game (a Player can only belong to
    one Game, but a Game can have several Players).
    """
    name = models.CharField(
        max_length=30)
    game = models.ForeignKey(
        to=Game,
        on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Round(models.Model):
    """
    Round has a many-to-one relationship with Game (a Round belongs to only one
    Game, but a Game may have several Rounds).
    """
    game = models.ForeignKey(
        to=Game,
        on_delete=models.CASCADE)
    
    # def __str__(self):
    #     return self.id


class Score(models.Model):
    """
    Score has a one-to-many relationship with Player (a Score can only belong to
    one Player, but a Player can have many Scores).
    Score has a one-to-many relationship with Round (a Score can only belong to
    one Round, but a Round can have many Scores).
    """
    # ensure only one score is added for a given Round/Player combination
    # class Meta:
        # unique_together = (("game_round", "player"), )
    
    game_round = models.ForeignKey(
        to=Round,
        on_delete=models.CASCADE)
    player = models.ForeignKey(
        to=Player,
        on_delete=models.CASCADE)
    value = models.IntegerField(
        default=0)

    # def __str__(self):
    #     return "Round %s, Player = %s, Score = %s" % (self.game_round, self.player, self.value)
    

# python manage.py shell
# from scorer.models import Game,Player,Round,Score
# myg = Game.objects.get(slug='1XuB8Bk')
# myg.player_set.all()
# myp=myg.player_set.all()[1]

# newround = Round(game=myg)
# newscore = Score(game_round=newround, player=myg.player_set.all()[1], value=5)

# myp = myg.player_set.all()[7]
# myr = myg.round_set.all()[1]
# newscore = Score(game_round=myr, player=myp, value=2)

project/templates/pages/games.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<script type="text/javascript">

    /* copy game links to clipboard */
    function myFunction(inputId) {
        
        /* Get the text field */
        var copyText = document.getElementById(inputId);

        /* Unhide it so we can copy */
        copyText.type ='text'

        /* Select the text field */
        copyText.select();
        copyText.setSelectionRange(0, 99999); /*For mobile devices*/

        /* Copy the text inside the text field */
        document.execCommand("copy");

        /* Hide it again */
        copyText.type ='hidden'

        /* Alert the copied text */
        alert("Copied the text: " + copyText.value);
        }
</script>

<div class="table-responsive">
    <table class="table table-striped table-hover" style="text-align: center;">
        <thead class="thead-dark">
            <tr>
                <th>
                    Date
                </th>
                <th>
                    Game
                </th>
                <th>
                    Players
                </th>
                <th>
                    Link
                </th>
                <th>

                </th>
            </tr>
            {% for game in games %}
            <tr>
                <td>
                    {{ game.date }}
                </td>
                <td>
                    <a href="{% url 'game' game.slug %}">{{ game.slug }}</a>
                </td>
                <td>
                    {% for player in player_list %}
                        {% if player.game_id == game.id %}
                            {{ player.name }}
                        {% endif %}
                    {% endfor %}
                </td>
                <td>
                    <input type="hidden" value="https://www.scorestuff.nz{{game.get_absolute_url}}" id="{{game.slug}}">
                    <a href="" id="{{game.slug}}" onclick="myFunction(this.id)">Copy link</a>
                </td>
                <td>
                    <a href="{% url 'delete_game' game.id %}"?>Delete</a>
                </td>
            </tr>
           
            {% endfor %}
        </thead>
    </table>
</div>



{% endblock content %}

project/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

<div class="home">
    <h2>ScoreStuff</h2>
    <p>scoring the things</p>
</div>

{% if user.is_authenticated %}

<div class="home-mid">
    <form method="post">
        {% csrf_token %}
        <input type="text" name="slug" maxlength="50" id="id_slug" style="display:none;">
        <input type="submit" class="btn btn-primary" value="Create new gameroom">
    </form>
</div>


{% else %}

<div class="home-mid">
    <h3>How it works</h3>
    <p>
        1. Sign up for a free account
    </p>
    <p>
        2. Create a room to keep track of your scores 
    </p>
    <p>
        3. Obviously win because you're the one doing the scoring
    </p>
    <p>
        4. Bask in the glory of winning your social card game by cheating
    </p>
    <p>
        5. Find some new friends
    </p>
</div>

<div class="home">
    <h3>Convinced?</h3>
    <br />
    <a class="btn btn-primary" href="{% url 'account_signup' %}">Sign up</a>
</div>

{% endif %}


{% endblock content %}

project/templates/pages/privacy.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Privacy{% endblock title %}

{% block content %}
<h2>Privacy</h2>
<p>Should probably write something here :)</p>
{% endblock content %}